### ISSUE TITLE
Nexus tries to connect to remote even if "Blocked" option checked

### ISSUE THREAD

**Issue by sewe** [sonatype-nexus-community/nexus-repository-p2#19]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**

I am trying to prevent Nexus from contacting a remote server after the local cache has been primed. I hence check _Blocked_ ("Block outbound connections on the repository") and uncheck _Auto blocking enabled_.

Nevertheless, the log is full of entries like the following occurring in rapid succession, i.e., every few seconds:

```
2019-11-25 11:05:12,073+0100 INFO  [qtp275201327-37226]  *UNKNOWN org.apache.http.impl.execchain.RetryExec - I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {s}->https://download.eclipse.org:443: The target server failed to respond
2019-11-25 11:05:12,074+0100 INFO  [qtp275201327-37226]  *UNKNOWN org.apache.http.impl.execchain.RetryExec - Retrying request to {s}->https://download.eclipse.org:443
```

From the log, I unfortunately cannot tell which specific repository on download.eclipse.org was queried.

* **What feature or behavior is this required for?**

Isolation from an upstream server that either faces regular outages or blocks clients (like Nexus) that use the service too much.

* **Anything else?**

Other options I tried, in various combinations:

- Setting _maximum component age_ to -1
- Setting _maximum component age_ to a large value (10080, i.e., 1 week)
- Setting _maximum metadata age_ to -1(not sure whether this is a valid value)
- Setting _maximum metadata age_ to a large value (10080, i.e., 1 week)

**Comment by proteus1121** [comment]
Fixed in 1.0.0 version of p2 (https://github.com/sonatype-nexus-community/nexus-repository-p2/pull/51)
Messages in log still present, but it works, it's related to specific httpClient which used by nexus. If you want to remove it, you should create custom httpClient and use it, like:
P2ProxyFacetImpl.java
`private CloseableHttpClient customHttpClient = HttpClients.custom().setConnectionReuseStrategy(NoConnectionReuseStrategy.INSTANCE).build();

  @Override
  protected HttpResponse execute(
      final Context context, final HttpClient client, final HttpRequestBase request) throws IOException
  {
    return super.execute(context, customHttpClient, request);
  }`

But it could affect other nexus feature, so I'm not recommend to submit this code.
