### ISSUE TITLE
What's the difference to the built in "raw poxy"

### ISSUE THREAD

**Issue by Weltraumschaf** [sonatype-nexus-community/nexus-repository-p2#7]
At our company we struggle heavy with build/Ci of an Maven based Eclipse RCP application build. At the moment we use <https://github.com/reficio/p2-maven-plugin> to generate own P2 sites with our own bundles for that build. But this is not the best solution: We can only rebuilt whole sites which takes lot of time.

So we decided to look at this Plugin, but after installing it and read the docs it looks like it only provides the capability of mirroring an existing P2 site. We do this already with the Nexus built in "raw proxy". So my questions:

* What is the difference of the P2 proxy to that Raw proxy?
* Is there a plan/idea to extend this Plugin to host a full fledged P2 repo in Nexus (whatever that means)?

**Comment by joedragons** [comment]
There's a ticket (https://issues.sonatype.org/browse/NEXUS-11730) to have P2 "full fledged" into NXRM3.  Whether it's this plugin integrated or not is not known to my knowledge.

**Comment by Weltraumschaf** [comment]
AFAIK they are talking about this plugin. But for me it is totally unclear what this plugin does better than the raw proxy repo.

**Comment by DarthHater** [comment]
@Weltraumschaf this plugin does a few things:

- stores P2 assets as components/assets in a way that should make them easier to find inside of Nexus Repo
- modifies metadata so that obtaining P2 packages is done through Nexus Repo, and not sidestepped by stuff like mirrorUrl in the P2 metadata

In theory, we could build p2 hosted, I would like to do this with the community's help/involvement however, as I'm sure people using P2 know Java :)

**Comment by mpiggott** [comment]
Using the raw proxy won't remove the mirrors reference which would cause tools to attempt to download from external repositories.

Raw repositories also would not provide any special handling for composite sites which would only work if they were relative and nested under the composite site.
